export const FEATURES = Object.freeze([
  {
    slug: 'youtube-calisma-plani',
    shortTitle: 'YouTube’dan çalışma planı',
    kicker: 'Video planlama',
    title: 'YouTube kampını uygulanabilir çalışma planına dönüştür',
    description: 'Bir YouTube videosunu veya oynatma listesini başlangıç noktası, günlük süre ve ders bilgisiyle Calisiyo çalışma planına aktar.',
    answer: 'Calisiyo, herkese açık bir YouTube videosunu veya oynatma listesini süre bilgileriyle analiz eder; seçtiğin başlangıç videosu ve günlük süreye göre görevler hazırlar. Oluşan görevleri kontrol ettikten sonra günlük ve haftalık programına tek işlemle ekleyebilirsin.',
    audience: 'YouTube kampını takip eden fakat videoları günlere elle dağıtmak istemeyen TYT, AYT ve YDT öğrencileri için uygundur.',
    highlights: ['Video veya oynatma listesi desteği', 'Başlangıç videosu ve dakika ofseti', 'Günlük ya da haftalık çalışma düzeni', 'Tekrar denemede kopya görevleri önleyen güvenli aktarım'],
    steps: [
      ['1', 'Bağlantıyı ekle', 'Herkese açık video veya oynatma listesi bağlantısını yapıştır.'],
      ['2', 'Başlangıcı belirle', 'İstersen belirli bir videodan ve o videonun belirli dakikasından başla.'],
      ['3', 'Çalışma ritmini seç', 'Ders, sınav türü ve günlük 15–360 dakika aralığındaki hedefini belirle.'],
      ['4', 'Kontrol edip aktar', 'Hazırlanan görevleri incele ve günlük/haftalık programına kaydet.'],
    ],
    example: { title: 'Örnek kullanım', text: '80 dakikalık bir TYT Matematik video çalışmasını, kampın 25. videosundan başlayacak şekilde planlayabilirsin. Video süreleri görevlerde korunur; tek bir uzun video sırf günlük hedefe sığsın diye yapay olarak bölünmez.' },
    limits: ['Yalnızca herkese açık ve erişilebilir YouTube içerikleri analiz edilebilir.', 'Kaldırılmış, gizli veya metadata bilgisi alınamayan içerikler açık bir hata durumuyla bildirilir.', 'İçe aktarma limitleri seçili plana göre değişebilir; güncel kapsam Paketler sayfasında gösterilir.'],
    relatedGuide: 'youtube-kampini-calisma-programina-donusturme',
    relatedFeature: 'yks-planlama',
  },
  {
    slug: 'calisma-siniflari',
    shortTitle: 'Canlı çalışma sınıfları',
    kicker: 'Birlikte çalışma',
    title: 'Canlı çalışma sınıfında birlikte odaklan',
    description: 'Arkadaşlarınla gerçek zamanlı bir çalışma odasına katıl; ortak odak, sınıf içi hareket, mesajlaşma ve paylaşım araçlarını birlikte kullan.',
    answer: 'Canlı çalışma sınıfı; üyelerin aynı odada çevrim içi durumunu, karakter konumunu ve mesajlarını gerçek zamanlı görmesini sağlar. Ortak odak sayacı, sınıf tahtası, metin–görsel–dosya–ses mesajları ve okundu bilgisi gibi araçlar birlikte çalışmayı tek alanda toplar.',
    audience: 'Tek başına çalışırken motivasyonu düşen veya küçük bir grupla düzenli odak seansları yapmak isteyen öğrenciler için tasarlanmıştır.',
    highlights: ['Gerçek zamanlı katılımcı ve konum güncellemeleri', '15, 25, 40 veya 50 dakikalık ortak odak', 'Metin, görsel, dosya ve ses paylaşımı', 'Yazılı ve çizimli ortak sınıf tahtası'],
    steps: [
      ['1', 'Sınıfı oluştur veya katıl', 'Sınıf koduyla mevcut odaya katılabilir ya da kendi odanı kurabilirsin.'],
      ['2', 'Durumunu paylaş', 'Çalışıyor, molada veya sınıfta durumlarından birini ve çalıştığın konuyu seç.'],
      ['3', 'Birlikte odaklan', 'Ortak sayacı başlat; herkes kendi dersine odaklanırken aynı ritmi takip etsin.'],
      ['4', 'Etkileşim kur', 'Sohbeti, sınıf tahtasını, koltukları ve karakter hareketlerini kullan.'],
    ],
    example: { title: 'Sınıfta neler yapılabilir?', text: 'Karakterini özelleştirebilir, sınıfta hareket edebilir, bir koltuğa oturabilir, el sallayabilir ve tahtaya yazı veya el çizimi ekleyebilirsin. Görsel alan istemeyen kullanıcılar sınıf görünümünü kapatıp sohbet ve odak araçlarıyla devam edebilir.' },
    limits: ['Sınıf kapasitesi ve bazı paylaşım limitleri plana göre değişir; Plus sınıfları en fazla 50 üyeye kadar ayarlanabilir.', 'Mesajlar ve canlı sınıf verileri yalnızca ilgili sınıfın yetkili üyelerine gösterilir.', 'Mikrofon ve dosya erişimi için tarayıcı izni gerekebilir.'],
    relatedGuide: 'calisma-sinifi-ile-birlikte-calisma',
    relatedFeature: 'kronometre-ve-istatistikler',
  },
  {
    slug: 'yks-planlama',
    shortTitle: 'Günlük ve haftalık planlama',
    kicker: 'Program yönetimi',
    title: 'Günlük ve haftalık YKS planını aynı görevlerle yönet',
    description: 'Ders, konu, tarih, saat, süre ve soru hedefi içeren görevleri günlük ve haftalık görünümde birlikte takip et.',
    answer: 'Calisiyo’da günlük ve haftalık program ayrı kayıtlar değildir. Eklediğin ders görevi tarihine göre iki görünümde de yer alır; tamamlanma durumu değiştiğinde program güncel kalır.',
    audience: 'Planını defter ve farklı uygulamalar arasında bölmeden, tek görev kaynağı üzerinden yürütmek isteyen YKS öğrencileri için uygundur.',
    highlights: ['Ders ve konu bazlı görevler', 'Başlangıç saati, süre ve soru hedefi', 'Günlük ve haftalık ortak görev kaynağı', 'Gerçek zamanlı durum güncellemeleri'],
    steps: [
      ['1', 'Görevi tanımla', 'Ders, konu, tarih ve yapılacak çalışmayı yaz.'],
      ['2', 'Ölçülebilir hedef ekle', 'Başlangıç saati, süre ve gerekiyorsa soru sayısı belirle.'],
      ['3', 'Haftaya dağıt', 'Yoğunluğu günler arasında uygulanabilir biçimde paylaştır.'],
      ['4', 'Gerçekleşeni işaretle', 'Tamamlanan görevi güncelle; kayıt istatistiklere tutarlı biçimde yansısın.'],
    ],
    example: { title: 'Belirsiz görev yerine açık görev', text: '“Matematik çalış” yerine “Fonksiyonlar · 17:00 · 50 dakika · 24 soru” gibi ölçülebilir bir görev eklemek, gün sonunda neyin tamamlandığını görmeyi kolaylaştırır.' },
    limits: ['Program, öğrencinin yerine akademik karar veya başarı tahmini üretmez.', 'Görevlerin uygulanabilirliği seçtiğin süre ve hedeflerin gerçekçi olmasına bağlıdır.', 'Plan limitleri üyelik kapsamına göre değişebilir.'],
    relatedGuide: 'yks-calisma-programi',
    relatedFeature: 'konu-takibi',
  },
  {
    slug: 'kronometre-ve-istatistikler',
    shortTitle: 'Kronometre ve istatistikler',
    kicker: 'Çalışma kaydı',
    title: 'Çalışma süreni kaydet, gerçek ritmini gör',
    description: 'Kronometre, manuel çalışma kayıtları ve tamamlanan görevlerden oluşan doğrulanmış çalışma verilerini tutarlı istatistiklerde incele.',
    answer: 'Kronometre çalışırken geçen süreyi kaydeder; manuel çalışma ve tamamlanan görev kayıtlarıyla aynı doğrulanmış çalışma düzeninde değerlendirilir. Günlük, haftalık ve toplam süreler ile en uzun çalışma günü aynı veri kaynağından hesaplanır.',
    audience: 'Masada geçirilen tahmini zamanı değil, gerçekten tamamlanan çalışmayı ölçmek isteyen öğrenciler için uygundur.',
    highlights: ['Başlatma, duraklatma ve tamamlama', 'Günlük, haftalık ve toplam çalışma süresi', 'En uzun çalışma günü ve çalışma ritmi', 'Ders, soru, konu ve program uyumu göstergeleri'],
    steps: [
      ['1', 'Çalışmayı başlat', 'Dersine başlarken Kronometreyi çalıştır.'],
      ['2', 'Araları doğru kaydet', 'Çalışmadığın zamanlarda sayacı duraklat.'],
      ['3', 'Eksik kaydı tamamla', 'Daha önce yaptığın bir çalışma için gerekiyorsa manuel kayıt ekle.'],
      ['4', 'Ritmi yorumla', 'Süreyi günlere dağılım, soru ve konu çıktılarıyla birlikte incele.'],
    ],
    example: { title: 'Çifte sayımı önleyen düzen', text: 'Aynı 60 dakikalık çalışma bir plan göreviyle ve çalışma kaydıyla ilişkiliyse toplam sürenin 120 dakika görünmemesi gerekir. Calisiyo istatistikleri ortak doğrulanmış çalışma kaynağını kullanır.' },
    limits: ['Veri girilmemiş günler için yapay süre veya seri oluşturulmaz.', 'İstatistikler sınav sonucu ya da başarı garantisi değildir.', 'Bazı geçmiş aralıkları ve dışa aktarma özellikleri plana göre değişebilir.'],
    relatedGuide: 'yks-calisma-suresi-takibi',
    relatedFeature: 'deneme-analizi',
  },
  {
    slug: 'deneme-analizi',
    shortTitle: 'Deneme analizi',
    kicker: 'Sonuç takibi',
    title: 'TYT, AYT ve YDT denemelerini ders bazında karşılaştır',
    description: 'Doğru ve yanlış sayılarını kaydet; boş ve net değerlerini güvenli biçimde hesaplayıp ders bazındaki değişimi takip et.',
    answer: 'Deneme analizinde her ders için doğru ve yanlış sayısı girilir. Bilinen soru sayısına göre boş sayısı otomatik hesaplanır; net ise doğru − yanlış/4 formülüyle saklanır ve sonuçlar aynı deneme altında karşılaştırılır.',
    audience: 'Deneme sonucunu yalnızca toplam net olarak değil, ders ve zaman içindeki değişimle değerlendirmek isteyen TYT, AYT ve YDT öğrencileri içindir.',
    highlights: ['TYT, AYT ve YDT deneme türleri', 'Otomatik boş ve net hesabı', 'Ders bazında sonuç kırılımı', 'Birden fazla deneme arasında karşılaştırma'],
    steps: [
      ['1', 'Denemeyi tanımla', 'Sınav türünü, tarihi ve deneme adını seç.'],
      ['2', 'Doğru ve yanlışı gir', 'Her ders için yalnızca geçerli tam sayı değerleri kaydet.'],
      ['3', 'Hesabı kontrol et', 'Boş ve net değerlerinin soru sayısıyla uyumlu oluşunu gör.'],
      ['4', 'Sonraki kararı ver', 'Ders değişimini konu ve çalışma planıyla birlikte yorumla.'],
    ],
    example: { title: '40 soruluk ders örneği', text: '34 doğru ve 3 yanlış girildiğinde 3 boş ve 33,25 net oluşur. 39 doğru ve 2 yanlış gibi toplamı 40’ı aşan bir giriş kaydedilmez.' },
    limits: ['Calisiyo puan, sıralama veya sınav başarısı tahmini sunmaz.', 'Tek bir deneme trend göstermez; karşılaştırma için benzer türde birden fazla kayıt gerekir.', 'Soru sayısı bilinmeyen bir ders için sistem yanlış bir toplam varsaymaz.'],
    relatedGuide: 'yks-deneme-analizi',
    relatedFeature: 'konu-takibi',
  },
  {
    slug: 'konu-takibi',
    shortTitle: 'Konu takibi',
    kicker: 'Müfredat ilerlemesi',
    title: 'YKS konularındaki ilerlemeni açık durumlarla takip et',
    description: 'TYT, AYT ve YDT konularını başlanmadı, devam ediyor ve tamamlandı durumlarıyla düzenle; gerektiğinde tekrarı ayrıca planla.',
    answer: 'Konu takibi, her konunun mevcut durumunu görünür tutar. Bir konuyu tamamlamak otomatik olarak tekrar görevi oluşturmaz; tekrar gerekiyorsa bunu açıkça “Tekrar planla” eylemiyle programa eklersin.',
    audience: 'Uzun müfredat listesinde neye başladığını, neyi bitirdiğini ve sıradaki çalışmayı karıştırmadan görmek isteyen öğrenciler içindir.',
    highlights: ['Başlanmadı, devam ediyor ve tamamlandı durumları', 'TYT, AYT ve YDT müfredat görünümü', 'Açık “Tekrar planla” eylemi', 'Sayfa yenilenmeden durum güncelleme'],
    steps: [
      ['1', 'Alan ve sınav yılını seç', 'İlgili ders ve konu listesini görüntüle.'],
      ['2', 'Mevcut durumu işaretle', 'Konuyu gerçek ilerlemene göre güncelle.'],
      ['3', 'Eksikleri belirle', 'Devam eden veya denemede sorun çıkaran konuları filtrele.'],
      ['4', 'Gerekirse tekrar planla', 'Tekrarı konu durumundan ayrı, tarihli bir görev olarak ekle.'],
    ],
    example: { title: 'Tamamlandı ile tekrar aynı şey değildir', text: 'Bir konuyu “Tamamlandı” yapmak ilerleme kaydını değiştirir; takvime kendiliğinden yeni görev eklemez. Böylece istenmeyen tekrar listeleri ve yinelenen görevler oluşmaz.' },
    limits: ['Durum seçimi öğrencinin kendi öğrenme ölçütünü temsil eder.', 'Müfredat görünümü akademik danışmanlık veya başarı garantisi değildir.', 'Tekrar görevleri yalnızca kullanıcı açıkça istediğinde oluşturulur.'],
    relatedGuide: 'yks-konu-takibi',
    relatedFeature: 'yks-planlama',
  },
]);

export const FEATURE_BY_SLUG = Object.freeze(Object.fromEntries(FEATURES.map((feature) => [feature.slug, feature])));
